### ISSUE TITLE
Migrate message formats to use transform matrices

### ISSUE THREAD

**Issue by gonzalonunez** [carrot-ar/carrot#62]
# Message Changes

### Format

Messages should now be of the format:
```json
{
  "session_token": "E628E5F8-C36C-496A-93FC-0C247A3E6E5F",
  "endpoint": "test_endpoint",
  "payload": {
     "transform": {
       "c0": [1, 2, 3, 4],
       "c1": [1, 2, 3, 4],
       "c2": [1, 2, 3, 4],
       "c3": [1, 2, 3, 4]
     },
     "params": {
        "foo": "bar"
      }
   }
}
```

The `transform` key is a dictionary containing four arrays, one for each **column** of the matrix. That's to say, the matrix actually looks like:

| c0 | c1 | c2 | c3
| :---: | :---: | :---: | :---: |
| 1 | 1 | 1 | 1 |
| 2 | 2 | 2 | 2 |
| 3 | 3 | 3 | 3 |
| 4 | 4 | 4 | 4 |

### How does this affect Picnic Protocol math?

What we're passing around now is a standard 4x4 transformation matrix. We need this in order to maintain other information about the geometry like its rotation and scaling so that other devices can render it properly.

The same 3D point we were dealing with is now in the last (fourth) column of the matrix, except it's now 4D because we're also including _w_. Example:

| c0 | c1 | c2 | c3
| :---: | :---: | :---: | :---: |
| 1 | 0 | 0 | _x_ |
| 0 | 1 | 0 | _y_ |
| 0 | 0 | 1 | _z_ |
| 0 | 0 | 0 | _w_ |

So, in order to do the math you want to be manipulating that last column and **preserving w**. So, extracting the _x_, _y_, and _z_ coordinates would look something like:

```swift
let x = matrix[3][0]
let y = matrix[3][1]
let z = matrix[3][2]
```

From there it's as simple as doing the  same math we're already doing and leaving everything else in the matrix exactly as is:

```swift
matrix[3][0] = newX
matrix[3][1] = newY
matrix[3][2] = newZ
```

Happy to help with writing code, reviewing PRs, or anything else I might be able to help with! Let me know if I need to clear anything else up.

**Comment by gonzalonunez** [comment]
The equivalent PR for iOS can be found [here](https://github.com/carrot-ar/carrot-ios/pull/10).

**Comment by clandry94** [comment]
This looks great. Offsets are defined [here](https://github.com/carrot-ar/carrot/blob/master/message.go#L32-L36). This should be fairly straightforward by redefining how this struct looks to hold a matrix and then updating the usages of it to perform matrix math instead of simple vector additions and subtraction. I believe [the get_ep](https://github.com/carrot-ar/carrot/blob/master/utils.go#L47-L72) calculation is the only location where we are doing anything with the offset currently.
